###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: auth-redis
      networks:
        - backend_auth

    mysql:
      image: mysql:5.7
      container_name: auth-mysql
      working_dir: /application
      networks:
        - backend_auth
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      ports:
        - "8102:3306"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: auth-php-fpm
      working_dir: /application
      networks:
        - backend_auth
        - reverse-proxy-nginx_reverse-proxy
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

    auth:
      image: nginx:alpine
      container_name: auth-webserver
      working_dir: /application
      networks:
        - reverse-proxy-nginx_reverse-proxy
        - backend_auth
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      expose:
        - "80"


networks:
  backend_auth:
  reverse-proxy-nginx_reverse-proxy:
    external: true


#    auth-rabbit:
#      image: "rabbitmq:3-management"
#      hostname: ${RABBITMQ_DEFAULT_HOSTNAME}
#      environment:
#        RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
#        RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
#        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
#        RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_STATUSLAYER_VHOST}
#      ports:
#        - "15672:15672"
#        - "5672:5672"
#      labels:
#        NAME: "rabbitmq1"
#      volumes:
#        - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
        #- "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"
        #- "./autocluster-0.4.1.ez:/usr/lib/rabbitmq/lib/rabbitmq_server-3.5.5/plugins/autocluster-0.4.1.ez"
